/*
 * This file is generated by jOOQ.
 */
package jooq;


import javax.annotation.Generated;

import jooq.tables.Books;
import jooq.tables.Languages;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SQLITE_AUTOINDEX_BOOKS_1 = Indexes0.SQLITE_AUTOINDEX_BOOKS_1;
    public static final Index SQLITE_AUTOINDEX_LANGUAGES_1 = Indexes0.SQLITE_AUTOINDEX_LANGUAGES_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index SQLITE_AUTOINDEX_BOOKS_1 = Internal.createIndex("sqlite_autoindex_books_1", Books.BOOKS, new OrderField[] { Books.BOOKS.ID }, true);
        public static Index SQLITE_AUTOINDEX_LANGUAGES_1 = Internal.createIndex("sqlite_autoindex_languages_1", Languages.LANGUAGES, new OrderField[] { Languages.LANGUAGES.ID }, true);
    }
}
