/*
 * This file is generated by jOOQ.
 */
package jooq;


import javax.annotation.Generated;

import jooq.tables.Books;
import jooq.tables.Languages;
import jooq.tables.records.BooksRecord;
import jooq.tables.records.LanguagesRecord;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<BooksRecord, Integer> IDENTITY_BOOKS = Identities0.IDENTITY_BOOKS;
    public static final Identity<LanguagesRecord, Integer> IDENTITY_LANGUAGES = Identities0.IDENTITY_LANGUAGES;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BooksRecord> PK_BOOKS = UniqueKeys0.PK_BOOKS;
    public static final UniqueKey<BooksRecord> SQLITE_AUTOINDEX_BOOKS_1 = UniqueKeys0.SQLITE_AUTOINDEX_BOOKS_1;
    public static final UniqueKey<LanguagesRecord> PK_LANGUAGES = UniqueKeys0.PK_LANGUAGES;
    public static final UniqueKey<LanguagesRecord> SQLITE_AUTOINDEX_LANGUAGES_1 = UniqueKeys0.SQLITE_AUTOINDEX_LANGUAGES_1;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<BooksRecord, Integer> IDENTITY_BOOKS = Internal.createIdentity(Books.BOOKS, Books.BOOKS.ID);
        public static Identity<LanguagesRecord, Integer> IDENTITY_LANGUAGES = Internal.createIdentity(Languages.LANGUAGES, Languages.LANGUAGES.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<BooksRecord> PK_BOOKS = Internal.createUniqueKey(Books.BOOKS, "pk_books", Books.BOOKS.ID);
        public static final UniqueKey<BooksRecord> SQLITE_AUTOINDEX_BOOKS_1 = Internal.createUniqueKey(Books.BOOKS, "sqlite_autoindex_books_1", Books.BOOKS.ID);
        public static final UniqueKey<LanguagesRecord> PK_LANGUAGES = Internal.createUniqueKey(Languages.LANGUAGES, "pk_languages", Languages.LANGUAGES.ID);
        public static final UniqueKey<LanguagesRecord> SQLITE_AUTOINDEX_LANGUAGES_1 = Internal.createUniqueKey(Languages.LANGUAGES, "sqlite_autoindex_languages_1", Languages.LANGUAGES.ID);
    }
}
