/*
 * This file is generated by jOOQ.
 */
package jooq;


import javax.annotation.Generated;

import jooq.tables.Books;
import jooq.tables.Languages;
import jooq.tables.SqliteSequence;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>books</code>.
     */
    public static final Books BOOKS = jooq.tables.Books.BOOKS;

    /**
     * The table <code>languages</code>.
     */
    public static final Languages LANGUAGES = jooq.tables.Languages.LANGUAGES;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public static final SqliteSequence SQLITE_SEQUENCE = jooq.tables.SqliteSequence.SQLITE_SEQUENCE;
}
