/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Books implements Serializable {

    private static final long serialVersionUID = -989636247;

    private Integer id;
    private Integer languageId;
    private String  slug;
    private String  name;
    private String  location;

    public Books() {}

    public Books(Books value) {
        this.id = value.id;
        this.languageId = value.languageId;
        this.slug = value.slug;
        this.name = value.name;
        this.location = value.location;
    }

    public Books(
        Integer id,
        Integer languageId,
        String  slug,
        String  name,
        String  location
    ) {
        this.id = id;
        this.languageId = languageId;
        this.slug = slug;
        this.name = name;
        this.location = location;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getLanguageId() {
        return this.languageId;
    }

    public void setLanguageId(Integer languageId) {
        this.languageId = languageId;
    }

    public String getSlug() {
        return this.slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Books (");

        sb.append(id);
        sb.append(", ").append(languageId);
        sb.append(", ").append(slug);
        sb.append(", ").append(name);
        sb.append(", ").append(location);

        sb.append(")");
        return sb.toString();
    }
}
