/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Languages implements Serializable {

    private static final long serialVersionUID = 1139519664;

    private Integer id;
    private String  slug;
    private String  name;
    private String  direction;

    public Languages() {}

    public Languages(Languages value) {
        this.id = value.id;
        this.slug = value.slug;
        this.name = value.name;
        this.direction = value.direction;
    }

    public Languages(
        Integer id,
        String  slug,
        String  name,
        String  direction
    ) {
        this.id = id;
        this.slug = slug;
        this.name = name;
        this.direction = direction;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getSlug() {
        return this.slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDirection() {
        return this.direction;
    }

    public void setDirection(String direction) {
        this.direction = direction;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Languages (");

        sb.append(id);
        sb.append(", ").append(slug);
        sb.append(", ").append(name);
        sb.append(", ").append(direction);

        sb.append(")");
        return sb.toString();
    }
}
